name: Docker image CI for CHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the images
        run: |
          docker login --username Andresmup --password ${{ secrets.GH_TOKEN}} ghcr.io
          docker build . -t ghcr.io/andresmup/docker-python-aws-ec2:latest
          docker push  ghcr.io/andresmup/docker-python-aws-ec2:latest